### ISSUE TITLE
Shift+enter inconsistent behavior

### ISSUE THREAD

**Issue by andrew-makarenko** [fraywing/textAngular#579]
Shift+enter should insert a `<br>`, but in Safari on Mac it inserts a new line.
Steps to reproduce:
https://jsfiddle.net/o6nbf0bu/
1. Open this link in Safari
2. Put text caret to the end of the line in the list item
3. Press shift+enter
4. New line with list item appears

Expected result: new line without `<li>`

Works good in latest Chrome, FF and IE.

**Comment by SimeonC** [comment]
Thanks for pointing this out, looks like this is still an issue in the latest 1.3 releases as well.

**Comment by JoelParke** [comment]
Fixed in later releases

**Comment by limonte** [comment]
@JoelParke can you please make any reference to PR or commit which solves this bug. Using last version of textAngular (v1.4.6), but still having this issue.

**Comment by pbassut** [comment]
@limonte I'm using version 1.4.6.
Do the following: download the repo and do ```grunt compile```; open ```demo/demo.html``` and test

**Comment by JoelParke** [comment]
<p>Also the demo out there is current at v1.4.6 if that helps test....</p>

**Comment by JoelParke** [comment]
There is latter fix: https://github.com/fraywing/textAngular/pull/899 that fixes an issue with the improper closing of list elements that is probably not related to  the issue above, but you can also try that if 1.4.6 sill shows the issue.  Thanks --- Joel
