### ISSUE TITLE
Crash when applying heading to paragraphs

### ISSUE THREAD

**Issue by arjun-u** [fraywing/textAngular#631]
So I have in my ng-model few paragraphs:

<code>
&lt;p&gt;Hey there,&lt;/p&gt;
&lt;br&gt;
&lt;p&gt;Congratulations! Your account has been created. Please use the credentials mentioned below to login.&lt;/p&gt;
&lt;br&gt;
&lt;p&gt;Username: username&lt;/p&gt;
&lt;br&gt;
&lt;p&gt;Password: password&lt;/p&gt;
&lt;br&gt;
&lt;p&gt;-Arjun&lt;/p&gt;
</code>

When I selected entire text and hit the heading buttons H1, H2, .. etc it crashed with 
<code>
TypeError: Cannot read property 'insertBefore' of null
    at angular.module.factory.service.d (https://cdnjs.cloudflare.com/ajax/libs/textAngular/1.3.11/dist/textAngular.min.js:17:9994)
    at Scope.q.directive.link.angular.extend.wrapSelection (https://cdnjs.cloudflare.com/ajax/libs/textAngular/1.3.11/dist/textAngular.min.js:17:31633)
    at Scope.f [as action] (https://cdnjs.cloudflare.com/ajax/libs/textAngular/1.3.11/dist/textAngular.min.js:9:2704)
    at Scope.executeAction (https://cdnjs.cloudflare.com/ajax/libs/textAngular/1.3.11/dist/textAngular.min.js:17:6165)
    at Parser.functionCall (https://code.angularjs.org/1.2.28/angular.js:10903:21)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (https://code.angularjs.org/1.2.28/angular.js:19259:17)
    at Scope.$get.Scope.$eval (https://code.angularjs.org/1.2.28/angular.js:12811:28)
    at Scope.$get.Scope.$apply (https://code.angularjs.org/1.2.28/angular.js:12909:23)
    at HTMLButtonElement.<anonymous> (https://code.angularjs.org/1.2.28/angular.js:19264:23)
    at https://code.angularjs.org/1.2.28/angular.js:2853:10
</code>

Here's a plunk: http://plnkr.co/edit/GsT4oazwg9k2pOc8Vylp?p=preview

I'm using 1.3.11

**Comment by oscar-g** [comment]
I too am having this error, but I haven't had time to look into it.  Here's the logged error from the un-minified source

TypeError: Cannot read property 'insertBefore' of null at angular.module.factory.service._document
js/plugins/textAngular/textAngular.js:636:29)
    at Scope.textAngular.directive.link.angular.extend.wrapSelection (js/plugins/textAngular/textAngular.js:1947:8)
    at Scope.headerAction [as action] (js/plugins/textAngular/textAngularSetup.js:359:25)
    at Scope.executeAction (js/plugins/textAngular/textAngular.js:422:18)
    at $parseFunctionCall (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:12404:18)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:21566:17)
    at Scope.$get.Scope.$eval (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:14466:28)
    at Scope.$get.Scope.$apply (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:14565:23)
    at HTMLButtonElement.<anonymous> (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:21571:23)
    at HTMLButtonElement.n.event.dispatch (js/jquery/jquery-2.1.1.min.js:3:6404)

**Comment by pbassut** [comment]
Can't reproduce this. Are you guys using the latest version of textAngular?

**Comment by pbassut** [comment]
Just noticed that this issue was solved on 1.4.x if I'm not mistaken.
Just change the version of textAngular to 1.4.3 and you should be good to go.

 I'm closing this issue.

**Comment by BukeMan** [comment]
the issue still exists on the latest version (1.5.0).
reproducing steps:
1) copy text from MS Word
2) paste into the editor
3) apply heading
4) get error in console
