### ISSUE TITLE
textAngular.min.js error: ReferenceError: Can't find variable: require at .../textAngular/dist/textAngular.min.js

### ISSUE THREAD

**Issue by rdeslonde** [fraywing/textAngular#871]
Getting this error when using textAngular.min.js. If I switch to using textAngular.js and textAngularSetup.js I don't get this error.

Richard B DesLonde@WIN-QOT7FJU27QQ /c/Projects/SportLynxFrontEnd (master)
$ grunt watch
>> Local Npm module "grunt-contrib-compress" not found. Is it installed?

Running "clean:0" (clean) task
Cleaning build...OK

Running "clean:1" (clean) task

Running "html2js:app" (html2js) task
Successfully converted 23 html templates to js.

Running "html2js:common" (html2js) task
Successfully converted 0 html templates to js.

Running "jshint:src" (jshint) task
>> 62 files lint free.

Running "jshint:test" (jshint) task
>> 13 files lint free.

Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:globals" (jshint) task
>> 0 files linted. Please check your ignored files.

Running "coffeelint:src" (coffeelint) task
>> 0 files lint free.

Running "coffeelint:test" (coffeelint) task
>> 0 files lint free.

Running "coffee:source" (coffee) task

Running "less:build" (less) task
File build/assets/SportLynx-0.0.1.css created: 0 B → 147.7 kB

Running "concat:build_css" (concat) task
File "build/assets/SportLynx-0.0.1.css" created.

Running "copy:build_app_assets" (copy) task
Created 1 directories, copied 8 files

Running "copy:build_vendor_assets" (copy) task
Copied 10 files

Running "copy:build_fonts" (copy) task
Copied 5 files

Running "copy:build_appjs" (copy) task
Copied 62 files

Running "copy:build_vendorjs" (copy) task
Copied 24 files

Running "ngAnnotate:build" (ngAnnotate) task
>> 62 files successfully generated.

Running "index:build" (index) task

Running "karmaconfig:unit" (karmaconfig) task

Running "karma:continuous" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:9018/
INFO [launcher]: Starting browser PhantomJS
WARN [watcher]: Pattern "c:/Projects/SportLynxFrontEnd/src/**/*.coffee" does not
 match any file.
INFO [PhantomJS 1.9.8 (Windows 7)]: Connected on socket Zb68FbTe75aD2J-m-UK5 wit
h id 36335915
PhantomJS 1.9.8 (Windows 7) AppController isCurrentUrl should pass a dummy test
FAILED
        ReferenceError: Can't find variable: require
            at c:/Projects/SportLynxFrontEnd/vendor/textAngular/dist/textAngular
.min.js:18
            at invoke (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3
965)
            at c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3811
            at forEach (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:
325)
            at createInjector (c:/Projects/SportLynxFrontEnd/vendor/angular/angu
lar.js:3811)
            at workFn (c:/Projects/SportLynxFrontEnd/vendor/angular-mocks/angula
r-mocks.js:2353)
        ReferenceError: Can't find variable: require
            at c:/Projects/SportLynxFrontEnd/vendor/textAngular/dist/textAngular
.min.js:18
            at invoke (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3
965)
            at c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3811
            at forEach (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:
325)
            at createInjector (c:/Projects/SportLynxFrontEnd/vendor/angular/angu
lar.js:3811)
            at workFn (c:/Projects/SportLynxFrontEnd/vendor/angular-mocks/angula
r-mocks.js:2353)
PhantomJS 1.9.8 (Windows 7) Registration should match guardian 1 email FAILED
        ReferenceError: Can't find variable: require
            at c:/Projects/SportLynxFrontEnd/vendor/textAngular/dist/textAngular
.min.js:18
            at invoke (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3
965)
            at c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3811
            at forEach (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:
325)
            at createInjector (c:/Projects/SportLynxFrontEnd/vendor/angular/angu
lar.js:3811)
            at workFn (c:/Projects/SportLynxFrontEnd/vendor/angular-mocks/angula
r-mocks.js:2353)
        ReferenceError: Can't find variable: createController
            at c:/Projects/SportLynxFrontEnd/src/app/registration/registration.s
pec.js:37
PhantomJS 1.9.8 (Windows 7) Registration should not change when guardian 1 email
 changes if it already has a value FAILED
        ReferenceError: Can't find variable: require
            at c:/Projects/SportLynxFrontEnd/vendor/textAngular/dist/textAngular
.min.js:18
            at invoke (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3
965)
            at c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3811
            at forEach (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:
325)
            at createInjector (c:/Projects/SportLynxFrontEnd/vendor/angular/angu
lar.js:3811)
            at workFn (c:/Projects/SportLynxFrontEnd/vendor/angular-mocks/angula
r-mocks.js:2353)
        ReferenceError: Can't find variable: createController
            at c:/Projects/SportLynxFrontEnd/src/app/registration/registration.s
pec.js:49
PhantomJS 1.9.8 (Windows 7): Executed 3 of 3 (3 FAILED) ERROR (0.061 secs / 0.05
6 secs)
Warning: Task "karma:continuous" failed. Use --force to continue.

Aborted due to warnings.

**Comment by pbassut** [comment]
What version are you using?

**Comment by rdeslonde** [comment]
I'm using 1.4.5

**Comment by rdeslonde** [comment]
Strange...just looked in my files.textAngular.js has 1.4.4. textAngular.min.js has two versions listed...

!function(a,b){b["true"]=a,/*
@license textAngular
Author : Austin Anderson
License : 2013 MIT
Version 1.3.7

See README.md or https://github.com/fraywing/textAngular/wiki for requirements and use.

...then the code...

@license textAngular
Author : Austin Anderson
License : 2013 MIT
Version 1.4.4

See README.md or https://github.com/fraywing/textAngular/wiki for requirements and use.

**Comment by pbassut** [comment]
Could you run ```grunt clean``` and then ```grunt``` again?

**Comment by pbassut** [comment]
Also, did you do a ```npm install``` and ```bower install```?

**Comment by rdeslonde** [comment]
Did a bower update yes.

**Comment by rdeslonde** [comment]
Tried `grunt clean` and then `grunt watch`, but getting the same error.

**Comment by pbassut** [comment]
Where are you running that from? TA project or your own?

**Comment by rdeslonde** [comment]
My own project.

**Comment by codydaig** [comment]
I'm having this issue in my project as well! github.com/nobsjs/nobsjs

**Comment by pbassut** [comment]
@codydaig Thanks for providing your code. That helps me to find the issue

**Comment by pbassut** [comment]
So, when exactly you experience this issue? Also when doing grunt watch?

**Comment by codydaig** [comment]
`gulp test` It works just fine in production, just fails all of our tests.

**Comment by pbassut** [comment]
This is fixed. Tested with @codydaig project and it's working fine now. 
Either you guys get the latest commit until we make a release(should be soon since this is critical) or you just wait.
If someone could test it, that would be great.
Thanks for the report.

**Comment by rdeslonde** [comment]
Thanks for fixing it so fast. I will wait for the release. :-)

**Comment by codydaig** [comment]
@JoelParke @pbassut Thanks for the quick update! Just updated the project this morning and everything seems to be working just fine. We'll let you know if there's any more random bugs we encounter.

Thanks again for being on top of it! :-D

**Comment by mraible** [comment]
I'm seeing this issue with the 1.4.6 release. Everything works fine when I run my app, but not when I try to run tests.

**Comment by pbassut** [comment]
Are you sure this isn't a cache problem with npm?

**Comment by mraible** [comment]
Yep, I'm pretty sure. I ran `rm -rf node_modules bower_components` followed by an `npm install`. It looks like I'm getting rangy 1.3.0:

`rangy#1.3.0 bower_components/rangy`

When I run `grunt test`, I get:

````
Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket 54GL-TEtNP8aMdMT275X with id 50700668
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: require
  at /Users/mraible/dev/myapp/bower_components/textAngular/dist/textAngular-rangy.min.js:2
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.102 secs / 0 secs)
Warning: Task "karma:unit" failed. Use --force to continue.
````

**Comment by EnglishCriminal** [comment]
+1 Really awesome plugin, builds and runs great. Using karma I've got the same problem as @mraible  running tests. Tried versions 1.4.3, 1.4.4, 1.4.5, and 1.4.6.

```
[11:58:01] Starting 'karma:1.4'...
06 10 2015 11:58:02.228:INFO [karma]: Karma v0.13.10 server started at http://localhost:8080/
06 10 2015 11:58:02.233:INFO [launcher]: Starting browser PhantomJS
06 10 2015 11:58:03.000:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket TqFx3KTmdPlXiLMUAAAA with id 82972573
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: require
  at /Users/lars/go/src/github.com/myorg/myproject/vendor/textAngular-1.4.4/textAngular-rangy.min.js:2
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.217 secs / 0 secs)
```

**Comment by Machiaweliczny** [comment]
Same problem here 
```
bin/rake karma:run
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket W0Ptuc5qUMYnI6yiMxeG with id 27515528
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: require
  at /Users/me/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails-assets-textAngular-1.4.6/app/assets/javascripts/textAngular/textAngular-rangy.min.js:2
```

**Comment by pbassut** [comment]
Could someone print the results of ```src/main.js``` that's inside the textAngular project?

**Comment by murran** [comment]
Same issue here - works great in production but not in tests. The rangy file is only available minified so not sure how to help with a better traceback
```
10 10 2015 18:38:08.511:INFO [karma]: Karma v0.13.9 server started at http://localhost:9876/
10 10 2015 18:38:08.517:INFO [launcher]: Starting browser PhantomJS
10 10 2015 18:38:09.483:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket gNTvI7ylB4I8_J_MAAAA with id 62338854
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: require
  at /Users/karl/code/project/frontend/components/textAngular/dist/textAngular-rangy.min.js:2
```

**Comment by rdeslonde** [comment]
This is fixed in the current build. I set mine back to using textangular.min.js after upgrading. Thanks guys!

**Comment by murran** [comment]
The current build still doesn't work for me during testing. However, I get it working (in both production and testing) when replacing the provided `textAngular-rangy.min.js` with the original rangy files `rangy-core.js` and `rangy-selectionsaverestore.js`

**Comment by EnglishCriminal** [comment]
I followed @murran's steps and everything is working now. It seems that rangy.min.js is the culprit.
